name: Android Release CI

on:
  push:
    tags:
      - 'v*' # Triggers on tags like v1.0, v1.0.1, etc.

  workflow_dispatch: # Allows manual triggering

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 16
        uses: actions/setup-java@v3
        with:
          java-version: 16
          distribution: 'temurin'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Decode Keystore
        env:
          KEYSTORE_BASE64: ${{ secrets.KEYSTORE_BASE64 }}
        run: |
          set -e
          echo "$KEYSTORE_BASE64" | base64 --decode > app/release.keystore

      - name: Run Unit Tests
        run: ./gradlew test

      - name: Build Release APK
        env:
          ORG_GRADLE_PROJECT_KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
          ORG_GRADLE_PROJECT_KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
          ORG_GRADLE_PROJECT_KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
        run: |
          set -e
          ./gradlew assembleRelease

      - name: Get tag name
        id: get_tag
        run: echo "tag=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT

      - name: Generate Changelog
        id: changelog
        run: |
          echo "changelog<<EOF" >> $GITHUB_OUTPUT
          git log -1 --pretty=format:"- %s" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: app/build/outputs/apk/release/app-release.apk
          name: Release ${{ steps.get_tag.outputs.tag }}
          tag_name: ${{ steps.get_tag.outputs.tag }}
          body: |
            # WebGPT Release ${{ steps.get_tag.outputs.tag }}

            ## What's New:
            ${{ steps.changelog.outputs.changelog }}

            ## Installation:
            Download the `WebGPT-${{ steps.get_tag.outputs.tag }}.apk` file from the assets below.
          draft: false
          prerelease: false
